**Import the libraries**

In [2]:
import numpy as np
import pandas as pd
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix, classification_report

**Load the Dataset**

In [4]:
# Load the Wine dataset
wine = datasets.load_wine()
X = wine.data  # Features
y = wine.target  # Labels
target_names = wine.target_names  # Class names

# Display the dataset information
print("Step 1: Wine Dataset Loaded")
print("Number of Features:", X.shape[1])
print("Number of Classes:", len(target_names))
print("Feature Data (first 5 rows):\n", pd.DataFrame(X, columns=wine.feature_names).head())
print("Target Labels (first 5):\n", y[:5])
print("Class Names:", target_names)


Step 1: Wine Dataset Loaded
Number of Features: 13
Number of Classes: 3
Feature Data (first 5 rows):
    alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   
3    14.37        1.95  2.50               16.8      113.0           3.85   
4    13.24        2.59  2.87               21.0      118.0           2.80   

   flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39     

**Split the Data**


In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
print("Training Set Size:", X_train.shape)
print("Testing Set Size:", X_test.shape)

Training Set Size: (124, 13)
Testing Set Size: (54, 13)


**Train LDA Model**

In [8]:
lda = LinearDiscriminantAnalysis()
lda.fit(X_train, y_train)
print("\nStep 3: LDA Model Trained on Training Set")

# Step 4: Evaluate the LDA Model
y_pred_lda = lda.predict(X_test)
accuracy_lda = accuracy_score(y_test, y_pred_lda)
precision_lda = precision_score(y_test, y_pred_lda, average='weighted')
recall_lda = recall_score(y_test, y_pred_lda, average='weighted')
confusion_lda = confusion_matrix(y_test, y_pred_lda)

print("\nStep 4: LDA Model Evaluation")
print("LDA Accuracy:", accuracy_lda)
print("LDA Precision:", precision_lda)
print("LDA Recall:", recall_lda)
print("LDA Confusion Matrix:\n", confusion_lda)
print("LDA Classification Report:\n", classification_report(y_test, y_pred_lda))


Step 3: LDA Model Trained on Training Set

Step 4: LDA Model Evaluation
LDA Accuracy: 1.0
LDA Precision: 1.0
LDA Recall: 1.0
LDA Confusion Matrix:
 [[19  0  0]
 [ 0 21  0]
 [ 0  0 14]]
LDA Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        21
           2       1.00      1.00      1.00        14

    accuracy                           1.00        54
   macro avg       1.00      1.00      1.00        54
weighted avg       1.00      1.00      1.00        54



**Evaluation of Dataset**

In [10]:
# Predict the labels on the test set
y_pred_log_reg = log_reg.predict(X_test)

# Compute the model's accuracy
accuracy_log_reg = accuracy_score(y_test, y_pred_log_reg)

# Compute the model's precision
precision_log_reg = precision_score(y_test, y_pred_log_reg, average='weighted')

# Compute the model's recall
recall_log_reg = recall_score(y_test, y_pred_log_reg, average='weighted')

# Compute the confusion matrix
confusion_log_reg = confusion_matrix(y_test, y_pred_log_reg)

# Display the evaluation results
print("\nLogistic Regression Model Evaluation")
print("Logistic Regression Accuracy:", accuracy_log_reg)
print("Logistic Regression Precision:", precision_log_reg)
print("Logistic Regression Recall:", recall_log_reg)
print("Logistic Regression Confusion Matrix:\n", confusion_log_reg)
print("Logistic Regression Classification Report:\n", classification_report(y_test, y_pred_log_reg))



Logistic Regression Model Evaluation
Logistic Regression Accuracy: 1.0
Logistic Regression Precision: 1.0
Logistic Regression Recall: 1.0
Logistic Regression Confusion Matrix:
 [[19  0  0]
 [ 0 21  0]
 [ 0  0 14]]
Logistic Regression Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        21
           2       1.00      1.00      1.00        14

    accuracy                           1.00        54
   macro avg       1.00      1.00      1.00        54
weighted avg       1.00      1.00      1.00        54



**Comparision with Logistic Regression**

In [11]:
# Train the Logistic Regression model
log_reg = LogisticRegression(max_iter=10000)  # Increase max_iter if convergence warning occurs
log_reg.fit(X_train, y_train)
print("\nStep 5: Logistic Regression Model Trained on Training Set")

# Evaluate the Logistic Regression model
y_pred_log_reg = log_reg.predict(X_test)

# Calculate evaluation metrics for Logistic Regression
accuracy_log_reg = accuracy_score(y_test, y_pred_log_reg)
precision_log_reg = precision_score(y_test, y_pred_log_reg, average='weighted')
recall_log_reg = recall_score(y_test, y_pred_log_reg, average='weighted')
confusion_log_reg = confusion_matrix(y_test, y_pred_log_reg)

# Display the evaluation results for Logistic Regression
print("\nLogistic Regression Model Evaluation")
print("Logistic Regression Accuracy:", accuracy_log_reg)
print("Logistic Regression Precision:", precision_log_reg)
print("Logistic Regression Recall:", recall_log_reg)
print("Logistic Regression Confusion Matrix:\n", confusion_log_reg)
print("Logistic Regression Classification Report:\n", classification_report(y_test, y_pred_log_reg))

# Step 6: Compare with LDA
# Assuming lda is already trained and the evaluation metrics are defined from previous steps

# Print summary of comparisons
print("\nSummary of Comparison with LDA:")
print(f"LDA Accuracy: {accuracy_lda:.2f}, Logistic Regression Accuracy: {accuracy_log_reg:.2f}")
print(f"LDA Precision: {precision_lda:.2f}, Logistic Regression Precision: {precision_log_reg:.2f}")
print(f"LDA Recall: {recall_lda:.2f}, Logistic Regression Recall: {recall_log_reg:.2f}")

# You can also compare the confusion matrices for both models
print("\nLDA Confusion Matrix:\n", confusion_lda)
print("\nLogistic Regression Confusion Matrix:\n", confusion_log_reg)



Step 5: Logistic Regression Model Trained on Training Set

Logistic Regression Model Evaluation
Logistic Regression Accuracy: 1.0
Logistic Regression Precision: 1.0
Logistic Regression Recall: 1.0
Logistic Regression Confusion Matrix:
 [[19  0  0]
 [ 0 21  0]
 [ 0  0 14]]
Logistic Regression Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        21
           2       1.00      1.00      1.00        14

    accuracy                           1.00        54
   macro avg       1.00      1.00      1.00        54
weighted avg       1.00      1.00      1.00        54


Summary of Comparison with LDA:
LDA Accuracy: 1.00, Logistic Regression Accuracy: 1.00
LDA Precision: 1.00, Logistic Regression Precision: 1.00
LDA Recall: 1.00, Logistic Regression Recall: 1.00

LDA Confusion Matrix:
 [[19  0  0]
 [ 0 21  0]
 [ 0  0 14]]

Logistic Regression Confusion Matrix:
 [[19