Create a vector (array) of 1XN dimension representing N-
dimensional feature vector of a sample. Write a program to

compute the mean and variance of the elements present in the
array.

In [1]:
import numpy as np

def compute_mean_and_variance(vector):
    mean = np.mean(vector)
    variance = np.var(vector)
    return mean, variance

N = 10
vector = np.random.rand(N)

mean, variance = compute_mean_and_variance(vector)
print("Vector (1xN):", vector)
print("Mean of the vector:", mean)
print("Variance of the vector:", variance)


Vector (1xN): [0.77311779 0.97922125 0.53486162 0.46857451 0.98334797 0.84443039
 0.51094944 0.05814383 0.32039945 0.06331976]
Mean of the vector: 0.5536366014405572
Variance of the vector: 0.10482406818565035


Create two vectors each of dimension 1XM each representing N-
dimensional feature vector of a sample. Write a program to

compute the Covariance between them.

In [2]:
import numpy as np
def covarience(vector1,vector2):
    cov=np.cov(vector1,vector2)
    return cov
N = 5
vector1 = np.random.rand(N)
vector2 = np.random.rand(N)
cov=covarience(vector1,vector2)
print("Vector 1:", vector1)
print("Vector 2:", vector2)
print(cov)

Vector 1: [0.23086409 0.83640457 0.22811094 0.62533549 0.06931593]
Vector 2: [0.74080488 0.76410482 0.51489251 0.80441054 0.42419257]
[[0.10217748 0.04178073]
 [0.04178073 0.02858764]]


Create two vectors each of dimension 1XN. Write a program to
compute the Correlation between them.

In [3]:
import numpy as np
def correlation(vector1,vector2):
    corr=np.corrcoef(vector1,vector2)
    return corr
N = 5
vector1= np.random.rand(N)
vector2= np.random.rand(N)
corr=correlation(vector1,vector2)
print("Vector 1:", vector1)
print("Vector 2:", vector2)
print(corr)

Vector 1: [0.14730127 0.78745147 0.29933772 0.56760821 0.45449168]
Vector 2: [0.41927532 0.15929474 0.5422131  0.77482673 0.19619056]
[[ 1.         -0.26139776]
 [-0.26139776  1.        ]]


Create a Matrix of MXN dimension representing the M-dimensional
feature vector for N number of samples i. e (i,j)th entry of the matrix
represents the ith feature of jth sample. Write a program to compute
the covariance matrix and correlation matrix. Comment on
takeaways from these matrixes.

In [4]:
import numpy as np
M = 5
N = 3
matrix = np.random.rand(M,N)
cov_matrix = np.cov(matrix)
corr_matrix = np.corrcoef(matrix)
print("Matrix (MXN):", matrix)
print("Covariance Matrix:")
print(cov_matrix)
print("Correlation Matrix:")
print(corr_matrix)


Matrix (MXN): [[0.15030755 0.06938185 0.32363507]
 [0.67191889 0.89219399 0.44583362]
 [0.02191132 0.89687688 0.67343345]
 [0.8497295  0.23681402 0.53619414]
 [0.22020698 0.30528491 0.30645216]]
Covariance Matrix:
[[ 0.01687268 -0.02841688 -0.00244861  0.01189578  0.00139341]
 [-0.02841688  0.04981221  0.02419498 -0.03295929 -0.00021321]
 [-0.00244861  0.02419498  0.20666213 -0.13457495  0.02172835]
 [ 0.01189578 -0.03295929 -0.13457495  0.09393304 -0.01313951]
 [ 0.00139341 -0.00021321  0.02172835 -0.01313951  0.00244631]]
Correlation Matrix:
[[ 1.         -0.98020387 -0.04146654  0.29880754  0.21688564]
 [-0.98020387  1.          0.23846621 -0.48183761 -0.01931408]
 [-0.04146654  0.23846621  1.         -0.9658831   0.96636389]
 [ 0.29880754 -0.48183761 -0.9658831   1.         -0.86679083]
 [ 0.21688564 -0.01931408  0.96636389 -0.86679083  1.        ]]
